server:
  config:
    # Configuration CORS
    server.cors.enabled: true
    server.cors.allowOrigins: "*"
    server.cors.allowMethods: "GET, POST, PUT, DELETE, OPTIONS"
    server.cors.allowCredentials: true
    server.cors.allowHeaders: "*"

  # Configuration Ingress
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
      nginx.ingress.kubernetes.io/cors-allow-origin: "*"