apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.service.port }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: BASE_URL
              value: "http://{{ .Values.ingress.host }}"
          resources:
            requests:
              memory: {{ .Values.app.resources.requests.memory }}
              cpu: {{ .Values.app.resources.requests.cpu }}
            limits:
              memory: {{ .Values.app.resources.limits.memory }}
              cpu: {{ .Values.app.resources.limits.cpu }}
