{{- if and .Values.products.autoscaling.enabled (eq .Values.namespace "production") }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: products
  namespace: {{ .Values.namespace }}
  labels:
    app: products
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: products
  minReplicas: {{ .Values.products.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.products.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.products.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}