apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: {{ .Values.namespace }}
  labels:
    app: products
spec:
  type: {{ .Values.products.service.type | default "ClusterIP" }}  # Utilisation d'un type par défaut
  ports:
    - port: {{ .Values.products.service.port | default 8002 }}            # Port exposé avec une valeur par défaut
      targetPort: {{ .Values.products.service.targetPort | default 8002 }} # Port du conteneur avec une valeur par défaut
      protocol: TCP
      name: http
  selector:
    app: products
