# Configuration pour le microservice app

namespace: "staging"

certManager:
  enabled: true
  email: example@example.com
  namespace: cert-manager
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

certificate:
  name: example-staging-tls
  secretName: example-staging-tls
  issuerRef:
    name: letsencrypt-example
    kind: ClusterIssuer

# Configuration pour l'ingress
ingress:
  namespace: ingress-nginx
  host: staging.example.com
  tls: true

app:
  replicaCount: 1  
    repository: ""
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  resources:
    limits:
      cpu: "300m"
      memory: "768Mi"
    requests:
      cpu: "150m"
      memory: "384Mi"

products:
  replicaCount: 1
  image:
    repository: ""
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8002
    targetPort: 8002
  resources:
    limits:
      cpu: "100m"
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"
  env:
    NODE_ENV: "staging"
    CUSTOMER_SERVICE: "http://customers-service.staging.svc.cluster.local:8001"
    SHOPPING_SERVICE: "http://shopping-service.staging.svc.cluster.local:8003"
    MONGODB_URI: "mongodb://mongo-products-service:27017/products_db_staging"
    PORT: 8002
    BASE_URL: "http://products-service.staging.svc.cluster.local:8002/"
    EXCHANGE_NAME: "ONLINE_STORE"
    RABBITMQ_SERVICE: "rabbitmq-staging.staging.svc.cluster.local:5672"

shopping:
  replicaCount: 1
  image:
    repository: ""
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8003
    targetPort: 8003
  resources:
    limits:
      cpu: "100m"
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"
  env:
    NODE_ENV: "staging"
    CUSTOMER_SERVICE: "http://customers-service.staging.svc.cluster.local:8001"
    SHOPPING_SERVICE: "http://shopping-service.staging.svc.cluster.local:8003"
    MONGODB_URI: "mongodb://mongo-shopping-service:27017/shopping_db_staging"
    PORT: 8003
    BASE_URL: "http://shopping-service.staging.svc.cluster.local:8003/"
    EXCHANGE_NAME: "ONLINE_STORE"
    RABBITMQ_SERVICE: "rabbitmq-staging.staging.svc.cluster.local:5672"

customers:
  replicaCount: 1
  image:
    repository: ""
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8001
    targetPort: 8001
  resources:
    limits:
      cpu: "200m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  env:
    NODE_ENV: "staging"
    MONGODB_URI: "mongodb://mongo-customers-service:27017/customers_db_staging"
    EXCHANGE_NAME: "ONLINE_STORE"
    PORT: 8001
    BASE_URL: "http://customers-service.staging.svc.cluster.local:8001/"
    CUSTOMER_SERVICE: "http://customers-service.staging.svc.cluster.local:8001"
    SHOPPING_SERVICE: "http://shopping-service.staging.svc.cluster.local:8003"
    RABBITMQ_SERVICE: "rabbitmq-staging.staging.svc.cluster.local:5672"

mongoCusto:
  name: "mongo-customers"
  image: "mongo:4.4"
  replicaCount: 1
  port: 27017
  resources:
    limits:
      cpu: "75m"
      memory: "192Mi"
    requests:
      cpu: "35m"
      memory: "96Mi"
  storage:
    size: "512Mi"
    accessMode: "ReadWriteOnce"

mongoShop:
  name: "mongo-shopping"
  image: "mongo:4.4"
  replicaCount: 1
  port: 27017
  resources:
    limits:
      cpu: "150m"
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"
  storage:
    size: "1Gi"
    accessMode: "ReadWriteOnce"

mongoProd:
  name: "mongo-products"
  image: "mongo:4.4"
  replicaCount: 1
  port: 27017
  resources:
    limits:
      cpu: "150m"
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"
  storage:
    size: "1Gi"
    accessMode: "ReadWriteOnce"

