# Configuration de base
image:
  repository: fluent/fluentd-kubernetes-daemonset
  tag: "v1.15.3-debian-s3-1"
  pullPolicy: "Always"

# Désactiver la configuration automatique
autoConfigure: false
extraVolumes: []
extraVolumeMounts: []

# Service Account avec IRSA
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: ${fluentd_role_arn}

# Resources minimales mais suffisantes
resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "200m"
    memory: "400Mi"

# Configuration personnalisée des volumes via les valeurs
daemonset:
  volumes:
    - name: fluentd-buffer
      emptyDir:
        sizeLimit: "512Mi"
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
  volumeMounts:
    - name: fluentd-buffer
      mountPath: /var/log/fluentd-buffers
    - name: varlog
      mountPath: /var/log
      readOnly: true
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true

# Configuration des fichiers Fluentd
fileConfigs:
  01_sources.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-buffers/containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

  02_outputs.conf: |
    <match kubernetes.**>
      @type s3
      s3_bucket ${logs_bucket}
      s3_region ${aws_region}
      s3_object_key_format logs/applications/%Y/%m/%d/%%{time_slice}_%%{index}.%%{file_extension}
      time_slice_format %Y%m%d%H%M

      <buffer tag,time>
        @type file
        path /var/log/fluentd-buffers/s3
        timekey 60
        timekey_wait 1m
        chunk_limit_size 256m
        flush_mode interval
        flush_interval 60s
        retry_forever true
        retry_max_interval 30
        overflow_action block
      </buffer>
    </match>

# Plugins requis
plugins:
  - fluent-plugin-s3

# Configuration de base pour la stabilité
tolerations:
  - operator: Exists

rbac:
  create: true

podSecurityContext:
  enabled: true