controller:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  config:
    use-forwarded-headers: "true"
    ssl-redirect: "false"
    no-tls-redirect-locations: "/.well-known/acme-challenge/*"
  admissionWebhooks:
    patch:
      enabled: true