{{- if eq .Values.namespace "production" }}
---
# StorageClass pour MongoDB Shopping
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-shopping-storage-class
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "false"
allowVolumeExpansion: true

---
# Volume Primary MongoDB Shopping
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-shopping-pv
  labels:
    app: mongo-shopping
    type: primary
    storage: mongo-shopping
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-shopping-storage-class
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: {{ .Values.mongoShop.storage.volumes.primary.volumeId }}
    fsType: ext4
    volumeAttributes:
      type: gp3
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - {{ .Values.mongoShop.storage.volumes.primary.az }}

---
# PVC Primary MongoDB Shopping
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-shopping-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: mongo-shopping
    type: primary
    storage: mongo-shopping
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongo-shopping-storage-class
  volumeName: mongo-shopping-pv
  resources:
    requests:
      storage: 3Gi
{{- end }}