apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    #activé pour obtenir le certificat letsencrypt
    #cert-manager.io/cluster-issuer: "letsencrypt-euphoni"
    #acme.cert-manager.io/http01-edit-in-place: "true"
    #a desactiver une fois le certificat obtenu
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.certificate.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /(images/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: app-service
                port:
                  number: 80
          - path: /((static|images|assets)/.*|.*\.(js|css|png|jpg|jpeg|gif|ico|json|webp|svg))$
            pathType: ImplementationSpecific
            backend:
              service:
                name: app-service
                port:
                  number: 80
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: app-service
                port:
                  number: 80