{{- if eq .Values.namespace "dev" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-mongo-express
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: shopping-mongo-express
  template:
    metadata:
      labels:
        app: shopping-mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        # Configuration de la base de données
        - name: ME_CONFIG_MONGODB_URL
          value: "mongodb://mongo-shopping-service:27017/"
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        # Configuration du chemin spécifique pour shopping
        - name: ME_CONFIG_SITE_BASEURL
          value: "/mongo-express/shopping"
        # Authentification
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: "admin"
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: "password"
        - name: VCAP_APP_HOST
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-mongo-express-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: shopping-mongo-express
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
{{- end }}