apiVersion: v1
kind: Service
metadata:
  name: shopping-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.shopping.service.type }}
  ports:
    - port: {{ .Values.shopping.service.port }}
      targetPort: {{ .Values.shopping.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: shopping